main: com.cavetale.dungeons.DungeonsPlugin
name: Dungeons
version: 0.1
api-version: 1.13
description: Spawn custom dungeons
author: StarTux
website: https://cavetale.com
depend: [BlockClip]
softdepend: [Decorator]
commands:
  dungeons:
    description: Dungeons
    permission: dungeons.dungeons
    usage: |-
      /dungeons locate - Locate nearest
      /dungeons info - Current dungeon info
permissions:
  dungeons.dungeons:
    description: Use /dungeons
    default: op
