main: com.cavetale.dungeons.DungeonsPlugin
name: Dungeons
version: 0.1
api-version: 1.17

description: Spawn custom dungeons
author: StarTux
website: https://cavetale.com

depend: []
softdepend: [Decorator, BlockClip]

commands:

  dungeons:
    description: Dungeons
    permission: dungeons.dungeons
    usage: |-
      /dungeons locate - Locate nearest
      /dungeons info - Current dungeon info
      /dungeons special - Print special item
      /dungeons special <%chance> - Set special item from hand. 0 to disable.

permissions:

  dungeons.dungeons:
    description: Use /dungeons
    default: op
